### ISSUE TITLE
Off-The-Shelf Data Collection Devices: FitBit

### ISSUE THREAD

**Issue by hooman007** [ubcmist/ML#2]
## Research and purchase an off-the-shelf device to collect the required biomarkers

**Comment all your findings.**

_**GUIDING QUESTIONS**_. try to answer as many as possible.
1. Can we get data from Fitbit?
-Do we need to hack it?
-Is there an official API ready for this purpose?
-Is there an open source project online that extracts data from fitbit?

2. If data extraction from fitbit is feasible:
-What model of fitbit works best for our purpose? (biometrics that can be measured, price)
-Can we find a second hand (e.g. on craigslist) with decent price? If price is not much lower than retail, we can get a new one.

**TASKS:**
- [x] Choose a device general model (fitbit, other brands).
- [x] Find a solution to extract data from the device
- [x] Find the most suitable model
- [x] Purchase the device

**Comment by faridfaraji** [comment]
https://towardsdatascience.com/collect-your-own-fitbit-data-with-python-ff145fa10873

**Comment by hooman007** [comment]
The research is done over several FITBIT models. Please find the result here:

https://docs.google.com/spreadsheets/d/1RTC4KSgaOXiYIjxeeEIBpQEpontjNQ1WJbvkz-ECCtM/edit?usp=sharing 

In brief, **Alta HR** and  **CHARGE 3** are chosen to be the best match for our purpose. 

2 units of Charge 3 are purchased on Friday, Nov 23, 2018.  Purchase receipt is uploaded on google drive:  **/Purchases/Data_Collection_Devices**
